#!/bin/bash
mkdir -p ~/bin

for f in bin/*
do
    cp $f ~/bin/
done

for f in conf/*
do
    bf=`basename $f`
    cp $f ~/.$bf
done

for f in ssh/*
do
    bf=`basename $f`
    rm ~/.ssh/$bf
    ln -s `pwd`/$f ~/.ssh/$bf
done

ZSH=/usr/local/share/zsh/site-functions/
for f in zsh/*
do
    bf=`basename $f`
    if cmp -s $f $ZSH/$bf 
    then
	echo "Up to date"
    else
        sudo cp $f $ZSH
    fi
done
