#!/bin/bash
mkdir -p ~/bin

for f in bin/*
do
    cp $f ~/bin/
done

for f in conf/*
do
    bf=`basename $f`
    cp $f ~/.$bf
done

for f in ssh/*
do
    bf=`basename $f`
    rm ~/.ssh/$bf
    ln -s `pwd`/$f ~/.ssh/$bf
done