#!/bin/bash
mkdir -p ~/bin

for f in bin/*
do
    cp $f ~/bin/
done

for f in conf/*
do
    bf=`basename $f`
    cp $f ~/.$bf
done

for f in ssh/*
do
    bf=`basename $f`
    target=~/.ssh/$bf
    test -e $target && rm $target
    ln -fs `pwd`/$f $target
done

if [ ! -e ~/zsh ]
then
    ln -sf `pwd`/user_zsh ~/zsh
fi

ZSH=/usr/local/share/zsh/site-functions/
if [ ! -d "$ZSH" ]
then
    ZSH=/usr/share/zsh/site-functions
fi
for f in zsh/*
do
    bf=`basename $f`
    if cmp -s $f $ZSH/$bf 
    then
	echo "Up to date"
    else
        sudo cp $f $ZSH
    fi
done
