eval $(dircolors -b)
export PROMPT='%n@%m%u:%30<..<%~%b%(!.#.$) ' 
export MAIL=~/Mail/inbox
if which emacs >/dev/null
then
    if [ -n "$DISPLAY" ]
    then
        EDITOR=emacsclient
    else
        EDITOR=emacs
    fi
elif which jed >/dev/null
then
    EDITOR=jed
else
    EDITOR=nano
fi
export EDITOR

HISTSIZE=1000000
SAVEHIST=1000000
HISTFILE=~/.history
setopt inc_append_history
setopt promptsubst
setopt HIST_IGNORE_DUPS

alias ls='ls --color=auto'
alias less='less -R'
#fra zsh completion function artikkel
zstyle ':completion:*' verbose yes
zstyle ':completion:*:descriptions' format '%B%d%b'
zstyle ':completion:*:messages' format '%d'
zstyle ':completion:*:warnings' format 'No matches for: %d'
zstyle ':completion:*' group-name ''

# The following lines were added by compinstall
zstyle ':completion:*' completer _complete
zstyle :compinstall filename '/home/sigmunau/.zshrc'

host_stuff() {
    hosts=(`cat ~/.zshhosts`)
    if [ "$hosts" ]; then
        zstyle ':completion:*:hosts' hosts $hosts
    fi
}

preexec() {
    host_stuff
}
host_stuff
#bruk egne funksjoner
fpath=(~/zsh $fpath)
autoload -U ~/zsh/*(:t)

#mer compintall
autoload -U compinit
compinit
# End of lines added by compinstall

autoload -U promptinit
promptinit
prompt wunjo

if [ -d ~/bin ] ; then 
    PATH=$PATH:~/bin
fi
bindkey    "^[[3~"          delete-char
bindkey    "^[3;5~"         delete-char
bindkey ";5C" forward-word
bindkey ";5D" backward-word

compdef _precommand xvfb-run

export WORKON_HOME=$HOME/.virtualenvs
export PROJECT_HOME=$HOME/Devel
. /usr/local/bin/virtualenvwrapper.sh

alias pdns='whois -h passiv2.cert.uninett.no'
export VAULT_ADDR=https://vault.uninett.no:8200
export DUO_PASSCODE=push

source <(kubectl completion zsh)
